# Generated by Django 3.2.8 on 2021-11-04 13:38

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cityprojectvote',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('project', 'session'), name='unique_vote_per_session'),
        ),
    ]
