# Generated by Django 3.2.8 on 2021-11-04 13:39

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_cityprojectvote_unique_vote_per_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cityprojectvote',
            name='unique_vote_per_session',
        ),
        migrations.AddConstraint(
            model_name='cityprojectvote',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('project', 'session'), name='unique_vote_per_session'),
        ),
    ]
