# Generated by Django 3.2.8 on 2022-10-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20221006_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProjectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('question_statement', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('YES_NO', 'Oui/non'), ('TEXTAREA', 'Champ libre'), ('RATING', 'Évaluation')], default='TEXTAREA', max_length=9)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.cityproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
