# Generated by Django 3.2.8 on 2021-11-24 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20211122_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
