# Generated by Django 3.2.8 on 2022-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_cityprojectquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprojectquestion',
            name='type',
            field=models.CharField(choices=[('YES_NO', 'Oui/non'), ('TEXTAREA', 'Champ libre'), ('RATING_STARS', 'Évaluation - 5 étoiles'), ('RATING_10_5_0', 'Évaluation - 10/5/0')], default='TEXTAREA', max_length=50),
        ),
    ]
