# Generated by Django 3.2.8 on 2021-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20211124_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='birth_year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='city',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='zip_code',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
