# Generated by Django 3.2.8 on 2021-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20211104_1439'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cityprojectvote',
            name='unique_vote_per_session',
        ),
        migrations.AddConstraint(
            model_name='cityprojectvote',
            constraint=models.UniqueConstraint(fields=('project', 'session'), name='unique_vote_per_session'),
        ),
    ]
