# Generated by Django 3.2.8 on 2021-11-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mainApp', '0004_auto_20211104_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprojectvote',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.session'),
        ),
    ]
