# Generated by Django 3.2.8 on 2021-12-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20211124_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='registration_provider',
            field=models.CharField(choices=[(0, 'MANUALLY_CREATED'), (1, 'GOOGLE_SSO')], default=0, max_length=254),
            preserve_default=False,
        ),
    ]
