# Generated by Django 3.2.8 on 2021-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_cityprojectvote_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProjectVote3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1500)),
            ],
        ),
    ]
