# Generated by Django 3.2.8 on 2021-11-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_cityprojectvote3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityProjectVote3',
        ),
        migrations.AddField(
            model_name='cityproject',
            name='summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
