# Generated by Django 3.2.8 on 2022-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_cityprojectadditionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprojectcomment',
            name='reviewed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propositioncomment',
            name='reviewed',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
