# Generated by Django 3.2.8 on 2021-11-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mainApp', '0008_petition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1500)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cityprojectvote',
            name='unique_vote_per_session',
        ),
        migrations.AddConstraint(
            model_name='cityprojectvote',
            constraint=models.UniqueConstraint(fields=('project', 'session'), name='unique_project_vote_per_session'),
        ),
        migrations.AddField(
            model_name='petitionvote',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.petition'),
        ),
        migrations.AddField(
            model_name='petitionvote',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.session'),
        ),
        migrations.AddConstraint(
            model_name='petitionvote',
            constraint=models.UniqueConstraint(fields=('petition', 'session'), name='unique_petition_vote_per_session'),
        ),
    ]
