# Generated by Django 3.2.8 on 2022-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_cityprojectcommentapproval_propositioncommentapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprojectcommentapproval',
            name='comment_validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propositioncommentapproval',
            name='comment_validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
