# Generated by Django 3.2.8 on 2021-12-09 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0009_auto_20211209_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityProjectComments',
            new_name='CityProjectComment',
        ),
    ]
