# Generated by Django 3.2.8 on 2022-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20221204_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
