# Generated by Django 3.2.8 on 2021-12-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_rename_cityprojectcomments_cityprojectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproject',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
