# Generated by Django 3.2.8 on 2021-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_petitionsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.DecimalField(decimal_places=0, max_digits=10)),
                ('city', models.CharField(max_length=254)),
                ('birth_year', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cityprojectvote',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='petition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='petition',
            name='summary',
            field=models.TextField(),
        ),
    ]
