# Generated by Django 3.2.8 on 2022-12-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_proposition_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprojectcommentreview',
            old_name='comment_validated',
            new_name='review_decision',
        ),
        migrations.RenameField(
            model_name='propositioncommentreview',
            old_name='comment_validated',
            new_name='review_decision',
        ),
        migrations.RenameField(
            model_name='propositionreview',
            old_name='proposition_validated',
            new_name='review_decision',
        ),
    ]
