# Generated by Django 3.2.8 on 2022-12-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20221204_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprojectcomment',
            old_name='validated',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='propositioncomment',
            old_name='validated',
            new_name='approved',
        ),
    ]
